### ISSUE TITLE
issue running demos

### ISSUE THREAD

**Issue by quantumproducer** [dgud/gl_demos#1]
~/gl_demos:.erl -make && erl -run cubes
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"init terminating in do_boot",{undef,[{cubes,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
~/gl_demos:.erl -make && erl -run cubes
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"init terminating in do_boot",{undef,[{cubes,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done

**Comment by dgud** [comment]
Was a long time since I looked at those demos.

The instruction should be: cd cubes && erl -make && erl -run cubes 
Though it doesn't work either.. :-/

**Comment by quantumproducer** [comment]
After running make in the root directory, your ^ command worked!

```
/gl_demos/cubes:.erl -make && erl -run cubes
Recompile: cubes
cubes.erl:90: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
cubes.erl:97: Warning: ambiguous call of overridden auto-imported BIF error/1
 - use erlang:error/1 or "-compile({no_auto_import,[error/1]})." to resolve name clash
cubes.erl:121: Warning: ambiguous call of overridden auto-imported BIF error/1
 - use erlang:error/1 or "-compile({no_auto_import,[error/1]})." to resolve name clash
cubes.erl:149: Warning: ambiguous call of overridden auto-imported BIF error/1
 - use erlang:error/1 or "-compile({no_auto_import,[error/1]})." to resolve name clash
cubes.erl:150: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
cubes.erl:162: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
cubes.erl:203: Warning: ambiguous call of overridden auto-imported BIF error/1
 - use erlang:error/1 or "-compile({no_auto_import,[error/1]})." to resolve name clash
cubes.erl:216: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.1  (abort with ^G)
1> Something strange 0
Something strange 0

203:1286 (16#506)
```

<img width="818" alt="screen shot 2017-01-04 at 11 31 49" src="https://cloud.githubusercontent.com/assets/11827932/21649970/778656e8-d271-11e6-8e37-a045623bdf31.png">

**Comment by dgud** [comment]
Ah mac, I tested on linux and it didn't work there..will fix when I get time.
